# Generated by Django 3.2 on 2024-06-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_menuitem_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
