# Generated by Django 3.2 on 2024-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_menuitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='diet',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=7),
        ),
    ]
