# Generated by Django 5.0.6 on 2024-06-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_menuitem_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='diet',
            field=models.CharField(choices=[('all', 'All'), ('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='all', max_length=7),
        ),
    ]
